# .github/workflows/deploy.yml
name: Deploy Live Quiz PWA (Secrets Inject)
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject Firebase secrets
        run: |
          cp firebase.config.template.js firebase.config.js
          sed -i "s/\${FIREBASE_API_KEY}/${{ secrets.FIREBASE_API_KEY }}/g" firebase.config.js
          sed -i "s/\${FIREBASE_AUTH_DOMAIN}/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" firebase.config.js
          sed -i "s/\${FIREBASE_PROJECT_ID}/${{ secrets.FIREBASE_PROJECT_ID }}/g" firebase.config.js
          sed -i "s/\${FIREBASE_STORAGE_BUCKET}/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" firebase.config.js
          sed -i "s/\${FIREBASE_MESSAGING_SENDER_ID}/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" firebase.config.js
          sed -i "s/\${FIREBASE_APP_ID}/${{ secrets.FIREBASE_APP_ID }}/g" firebase.config.js

      - name: Prepare artifact
        run: |
          rm -rf _site
          mkdir -p _site
          shopt -s extglob
          cp -r !(._site|.git|.github) _site || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
